# Dont format this file, only change values
# Incorrect formatting will result in the entire configuration being reset!

# Must be a boolean (true/false)
debug: true

# Must be a String (text)
world-name: "world"

# Either "one" or "multiple"
# one meaning only one world will be used for all players worlds
# multiple meaning each player gets their own world

data:
  type: mysql
  mysql:
    host:
    port:
    database:
    username:
    password:
  sqlite:
    path:

# Must be an integer (whole number)
start:
  sizex: 15
  sizez: 15
  island-level: 0
max:
  sizex: 200
  sizez: 200
  island-level: 100